ckanext/metadata/auth.py
def metadata_create(context, data_dict=None):
    print("dipanggil di auth cek : {}", context)
    return {'success': True}

ckanext/metadata/views.py
import os
from flask import (Blueprint, render_template, jsonify, request, flash, url_for)
import ckan.plugins.toolkit as tk
import ckan.lib.navl.dictization_functions as dict_fns
import ckan.logic as logic
from ckanext.metadata.db import Metadata
from werkzeug.utils import secure_filename

import ckan.plugins as plugins

BASE_PATH = os.path.abspath(os.path.dirname(__file__))
UPLOAD_FOLDER = 'public/uploads'
ALLOWED_EXTENSION = {'pdf'}

# tambah url_prefix
bp = Blueprint(
    "metadata", __name__, url_prefix="/metadata"
)

def page():
    # return "metadata blueprint test view"
    dt_metadata = tk.get_action('metadata_get_all')(context={}, data_dict={})

    return render_template('metadata/index.html', data=dt_metadata)

def create():
    # return "halaman tambah metadata"
    try:
        plugins.toolkit.check_access('metadata_create', context={}, data_dict={})
    except plugins.toolkit.NotAuthorized as err:
        print("Error : {}".format(err))
        # tampilkan halaman halaman not authorize


    return render_template('metadata/metadata_form.html')

def upload():
    # proses form upload data
    """
        flow :
        -- lakukan validasi form yang dikirim.
        if validasi berhasil: 
            -- proces upload file
            if success:
                - return file path
            else : 
                - return error
            -- lanjut proses simpan ke database, dengan value url \
                berasal dari nilai yang dikembalikan proses upload.
        else :
            - return error
    """
    if not tk.request.method=='POST':
        return jsonify({"message": "method not support"}), 400
    else :
        data = request.form
        print(request.form)
        file = request.files['file']
        url_file = request.form.get('url')
        upload_filename = ''
        print("file : {}", file)
        print("url : {}", url_file )
        print("base upload path: {}", BASE_PATH)

        if _validate_file_upload(file):
            print("validate file: {}", _validate_file_upload(file))
            upload_filename = _upload_file(file)['filename']
        # if _validate_file_upload(url_file):
        #     print("validate file: {}", _validate_file_upload(url_file))
        #     upload_filename = _upload_file(url_file)['filename']

        new_metadata = {
            "owner_org":data.get('owner_org'),
            "title" : data.get('title'),
            "desc" : data.get('desc'),
            "author" : data.get('author'),
            "file_path" : upload_filename
        }
        # request_data = tk.request

        # req = {
        #     'title': request.title,
        #     'desc': request.desc
        # }
        
        data_dict = logic.clean_dict(
            dict_fns.unflatten(
                logic.tuplize_dict(
                    logic.parse_params(tk.request.form)
                )
            )
        )

        # res = tk.get_action('metadata_create')(context={}, data_dict=data_dict)
        res = tk.get_action('metadata_create')(context={}, data_dict=new_metadata)

        print("data to upload: {}", data)

        # return jsonify({"message": "Test gagal", "request":data_dict,
        #                 "request_data": data}), 201
        return tk.redirect_to('metadata.index')

def get(id):
    metadata = tk.get_action('metadata_get')(context={}, data_dict={"id": id})

    # return jsonify({"status": "success", "message": "data ditemukan", "data": metadata}), 201
    return render_template('metadata/metadata_read.html', data=metadata)

def edit(id):
    metadata = tk.get_action('metadata_get')(context={}, data_dict={"id": id})

    return render_template('metadata/metadata_form.html', mode='edit', metadata=metadata)

def update(id):

    # cek method, method harus diganti dengan PUT
    if not tk.request.method=='POST':
        return jsonify({"message": "method not support"}), 400
    else :
        data = request.form
        # print(request.form)

        update_metadata = Metadata(
            organization_id=data.get('owner_org'),
            title=data.get('title'),
            desc=data.get('desc'),
            author=data.get('author')
        )
        # request_data = tk.request

        # req = {
        #     'title': request.title,
        #     'desc': request.desc
        # }
        
        data_dict = logic.clean_dict(
            dict_fns.unflatten(
                logic.tuplize_dict(
                    logic.parse_params(tk.request.form)
                )
            )
        )

        res = tk.get_action('metadata_update')(context={}, data_dict=data_dict)
        res = {}

        print("response: {}", res)
        # -----
        # metadata = tk.get_action('metadata_update')(context={}, data_dict)
        # return jsonify({'mode': 'update'})
        # ----

        # return jsonify({"message": "Test gagal", "request":data_dict,
        #                 "request_data": new_metadata}), 201
        return tk.redirect_to(url_for('metadata.get', id=id))


def delete(id):
    metadata = tk.get_action('metadata_delete')(context={}, data_dict={"id": id})

    # return jsonify(metadata)
    # flash(metadata)

    return tk.redirect_to('metadata.index')

def _validate_file_upload(file):
    # cek jika file ada (file.filename=='')
    # cek allowed file extension 

    if file.filename == '':
        return False
    else :
        return True

def _isallowed_file(file):
    pass

def _upload_file(file):
    # Proses upload file
    filename = secure_filename(file.filename)
    file.save(os.path.join(BASE_PATH, UPLOAD_FOLDER, filename))
    return {'status': 'success', 'filename': filename}

    

bp.add_url_rule(
    "/", endpoint="index", view_func=page)
bp.add_url_rule(
    "/<int:id>", endpoint="get", view_func=get)
bp.add_url_rule(
    "/add", 'create', view_func=create)
bp.add_url_rule(
    "/add", 'upload', view_func=upload, methods=['POST'])
bp.add_url_rule(
    "/edit/<int:id>", "edit", view_func=edit)
bp.add_url_rule(
    "/update/<int:id>", endpoint="update", view_func=update, methods=['POST','PUT'])
bp.add_url_rule(
    "/delete/<int:id>", endpoint="delete", view_func=delete, methods=['POST','DELETE'])

def get_blueprints():
    return [bp]

ckanext/metadata/templates/header.html
{% ckan_extends %}

{% block header_site_navigation_tabs %}
    {# {{ super() }} #}
    {{ h.build_nav_main(
        ('dataset.search', _('Datasets')),
        ('organization.index', _('Organizations')),
        ('group.index', _('Groups')),
         ) }}
    <!-- <li>
        <a href="#">Link Terkait</a>
    </li> -->
    <li><a href="{{ url_for('metadata.index') }}">Metadata</a></li>
    <li role="presentation" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Publikasi <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ url_for('publikasi.index') }}">Publikasi Sektoral</a></li>
            <li><a href="{{ url_for('produk_hukum.index') }}">Produk Hukum</a></li>
        </ul>
    </li>
    <!-- <li><a href="{{ url_for('news.index') }}">Media</a></li> -->
    <li role="presentation" class="dropdown">
        <a href="#" class="dropdown-toggel" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Media <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ url_for('news.index')}}">Berita</a></li>
            <li>Galeri</li>
            <li>Video</li>
        </ul>
    </li>
    <li><a href="{{ url_for('epss.index') }}">OPD Sasaran EPSS</a></li>
    <!-- <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        OPS sasaran EPSS <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="https://ppkb.bimakota.go.id" target="_blank">DPPKB Kota Bima</a></li>
            <li><a href="https://pertanian.bimakota.go.id/web/detail/17/tentang_kami" target="_blank">Dinas Pertanian Kota Bima</a></li>
            <li><a href="https://dkp.bimakota.go.id/" target="_blank">Dinas Ketahanan Pangan Kota Bima</a></li>
            <li><a href="https://koperindag.bimakota.go.id/" target="_blank">Dinas Koperindag Kota Bima</a></li>
        </ul>
    </li> -->
{% endblock %}

ckanext/metadata/templates/home/layout-custom.html
{% ckan_extends %}

{% block custom_pane %}
    <p>Tambah metadat</p>
{% endblock %}

ckanext/metadata/templates/metadata/index.html
{% extends 'page.html' %}


{% block subtitle %}metadata{% endblock %}

{% block breadcrumb_content %}
  {{ super() }}
  <li class="active">{% link_for _('Metadata'), named_route='metadata.index' %}</li>
{% endblock %}

{% block page_header %}{% endblock %}

{% block page_primary_action %}
  {# if h.check_access('organization_create') #}
  {% if h.check_access('metadata_create') %}
    {% link_for _('Add Metadata'), named_route='metadata'+'.create', class_='btn btn-primary', icon='plus-square' %}
  {% endif %}
  {# endif #}
{% endblock %}

{% block primary_content_inner %}
  {% with messages = get_flashed_messages()  %}
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="delete_flash(this)">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>Success. </strong> {{ message }}
      </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <!-- {{ data|pprint}} -->
    {{ h.snippet('metadata/snippets/metadata_list.html', data=data['data']) }}
{% endblock %}

{% block secondary_content %}
    {% snippet "metadata/snippets/helper.html"  %}
{% endblock %}

{% block scripts %}
  {{ super() }}
  {% asset 'metadata/ckanext_metadata_js' %}
{% endblock %}

ckanext/metadata/templates/metadata/metadata_form.html
{% import 'macros/form.html' as form %}
{% extends 'page.html' %}

{% set data = data or {} %}
{% set errors = errors or {} %}
{% set mode = mode or 'add' %}
{% if mode=='edit' %}
    {% set action_url %}
        {{ url_for('metadata.update', id=metadata.id) }}
    {% endset %}
{% else %}
    {% set action_url %}
        {{ url_for('metadata.upload')}}
    {% endset %}
    
{% endif %}

{% block breadcrumb_content %}
    li.active
{% endblock %}

{% block content_action %}
    {% if mode=='edit' %}
        {% link_for _('View'), named_route='metadata.get', id=metadata.id, class_='btn btn-default', icon='eye' %}
    {% endif %}
{% endblock %}

{% block content_primary_nav %}
    {% if mode=='edit' %}
        {{ h.build_nav_icon('metadata.edit', _('Edit Metadata'), id=metadata.id, icon='') }}
    {% else %}
        {{ h.build_nav_icon('metadata.create', _('Add Metadata'), icon='') }}
    {% endif %}
{% endblock %}

{% block primary_content_inner %}
    <form action="{{ action_url }}" class="form" method="POST" enctype="multipart/form-data">
    {% block basic_fields_url %}
      {% set data = data or {} %}
      {% set errors = errors or {} %}
      {% set is_upload = (data.url_type == 'upload') %}
      {{ form.image_upload(data, errors, field_url='url', field_upload='upload', field_clear='clear_upload',
         is_upload_enabled=h.uploads_enabled(), is_url=data.url and not is_upload, is_upload=is_upload,
         upload_label=_('Data'), url_label=_('URL'), placeholder=_('http://example.com/external-data.csv'), field_name='name') }}
    {% endblock %}
        <input type="hidden" name="id" value="{% if mode=='edit' and metadata.id %}{{metadata.id}}{% endif %}">
        <div class="form-group">
            <label for="">{{ _('Upload File') }}</label>
            <input type="file" name="file" class="form-control">
        </div>
        <div class="form-group">
            <label for="">{{ _('Title') }}</label>
            <input type="text" name="title" class="form-control" 
                value="{% if mode=='edit' and metadata.title %}{{metadata.title|trim}}{% endif %}">
        </div>

        {% block metadata_field_desc %}
        <div class="form-group">
            <label for="metadata_field_desc">{{ _('Description') }}</label>
            <textarea name="desc" id="metadata_field_desc" class="form-control" 
                rows="6">{% if mode=='edit' and metadata.desc %}{{metadata.desc|trim}}{% endif %}</textarea>
        </div>
        {% endblock %}
        <!-- <div class="form-group">
            <label for="">{{ _('Organization') }}</label>
            <select name="" id="" class="form-control"></select>
        </div> -->
        {% block package_basic_fields_org %}
        {# if we have a default group then this wants remembering #}
        {% if data.group_id %}
        <input type="hidden" name="groups__0__id" value="{{ data.group_id }}" />
        {% endif %}

        {% set dataset_is_draft = data.get('state', 'draft').startswith('draft') or data.get('state', 'none') ==  'none' %}
        {% set dataset_has_organization = data.owner_org or data.group_id %}
        {% set organizations_available = h.organizations_available('create_dataset') %}
        {% set user_can_update_owner_org = h.can_update_owner_org(data, organizations_available) %}
        {% set user_is_sysadmin = h.check_access('sysadmin') %}
        {% set show_organizations_selector = organizations_available and user_can_update_owner_org %}
        {% set show_visibility_selector = dataset_has_organization or (organizations_available and (user_is_sysadmin or dataset_is_draft)) %}

        {% if show_organizations_selector and show_visibility_selector %}
        <div data-module="dataset-visibility">
        {% endif %}

        {% if show_organizations_selector %}
        {% set existing_org = data.owner_org or data.group_id %}
        <div class="form-group control-medium">
            <label for="field-organizations" class="control-label">{{ _('Organization') }}</label>
            <div class="controls">
                <select id="field-organizations" name="owner_org" data-module="autocomplete">
                {% if h.check_config_permission('create_unowned_dataset') %}
                <option value="" {% if not selected_org and data.id %} selected="selected" {% endif %}>{{ _('No organization') }}</option>
                {% endif %}
                {% for organization in organizations_available %}
                {# get out first org from users list only if there is not an existing org #}
                {% set selected_org = (existing_org and existing_org == organization.id) or (not existing_org and not data.id and organization.id == organizations_available[0].id) %}
                <option value="{{ organization.id }}" {% if selected_org %} selected="selected" {% endif %}>{{ organization.display_name }}</option>
                {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        {% endblock %}

        {% block metadata_author_field %}
        <div class="form-group">
            <label for="metadata_author_field">{{ _('Author') }}</label>
            <input type="text" id="metadata_author_field" name="author" class="form-control"
                value="{% if mode=='edit' and metadata.author %} {{metadata.author}} {% endif %}">
        </div>
        {% endblock %}

        <div class="row text-right">
            {% if mode=='edit' %}
                <a href="{{ url_for('metadata.delete', id=metadata.id)}}" class="btn btn-danger pull-left" data-module="confirm-action" data-module-content="{{ _('Are you sure?')}}">Delete</a>
            {% endif %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}

ckanext/metadata/templates/metadata/metadata_read.html
{% extends 'page.html' %}

{% block page_primary_action %}
{% endblock %}

{% block breadcrumb_content %}
    {{ super() }}
    <li>{% link_for _('Metadata'), named_route='metadata.index' %}</li>
    <li class="active"><a href="#">{{ h.resource_display_name(data) }}</a></li>
{% endblock %}

{% block content_action %}
    {% link_for _('Manage'), named_route='metadata.edit', id=data.id, class_='btn btn-default', icon='wrench' %}
{% endblock %}
{% block content_primary_nav %}
  {{ h.build_nav_icon('metadata.get', _('Metadata'), id=data.id, icon='') }}
{% endblock %}
<!-- <div>
    <a href="{{ url_for('metadata.edit', id=data.id)}}" class="btn btn-default">
        <span class="glyphicon glyphicon-wrench"></span> Manage
    </a> 
</div> -->

{% block primary_content_inner %}

<h2 class="display-3">{{ data.title }}</h2>
{% if data.desc %}
    <p>{{ data.desc }}</p>
{% else %}
    <p><i>Deskripsi belum tersedia</i></p>
{% endif %}

<div class="well">
    <strong>
        Download <span class="glyphicon glyphicon-save-file"></span>
    </strong>
    <a href="{% url_for_static('/uploads/' + data.file_path) %}">{{ data.file_path }}</a>
</div>

<div>
    <h3>Preview</h3>
    <object data="{{ '/uploads/'+ data.file_path }}" frameborder="0" width="100%" height="800"></object>
</div>
    
{% endblock %}

ckanext/metadata/templates/metadata/snippets/helper.html
<div class="module module-narrow module-shallow">
  <h2 class="module-heading">
    <i class="fa fa-info-circle"></i>
    {{ _('What are Metadata?') }}
  </h2>
  <div class="module-content">
    <p>
      {% trans %}
        <b>Metadata</b> adalah informasi dalam bentuk struktur dan format yang baku untuk menggambarkan Data, 
        menjelaskan Data, serta memudahkan pencarian, penggunaan, dan pengelolaan informasi Data.
      {% endtrans %}
    </p>
  </div>
</div>

ckanext/metadata/templates/metadata/snippets/metadata_list.html
{# 

Display a grid of metadata items.

metadata - A list of metadatas.

Example:

    {% snippet "metadata/snippets/metadata_list.html" %}

#}
{% block metadata_list %}
<div class="{{ list_class or 'dataset-list list-unstyled' }}">
    {% block metadata_list_inner %}
        {% for metadata in data %}
        <div class="panel panel-default">
            <div class="panel-body">
                <!-- <div class="row">
                    <div class="col-md-12 text-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">view</a></li>
                                <li><a href="#">edit</a></li>
                                <form id="metadata_delete_form" method="POST" action="{{ url_for('metadata.delete', id=metadata.id) }}">
                                    <input type="hidden" name="id" id="metadata_delete_id" value="{{ metadata.id }}">
                                    <input type="hidden" name="url" id="metadata_delete_url" value="{{ url_for('metadata.delete', id=metadata.id) }}">
                                    <li>
                                        <button type="submit"><span class="glyphicon glyphicon-remove"></span> delete</button>
                                    </li>
                                </form>
                            </ul>
                        </div>
                    </div>
                    
                </div> -->
                
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <!-- <img class="media-object" src="https://placehold.co/80x80/png" alt="..."> -->
                            <img class="media-object" src="/images/placeholder_file.svg" alt="..." height="100" width="100">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="{{ url_for('metadata.get', id=metadata.id) }}">
                            {{ metadata.title}}
                            </a>
                        </h4>
                        {% if metadata.desc %}
                            <p>{{ metadata.desc }}</p>
                        {% else %}
                            <p><i>Deskripsi belum tersedia.</i></p>
                        {% endif %}
                        <small>
                            <span class="glyphicon glyphicon-calendar"></span> {{ h.string_datetime(metadata.created) }}
                        </small>
                    </div>
                </div> 
            </div>
        </div>
        {% endfor %}
        {% for metadata in data %}
        <!-- <div class="panel panel-default">
            <div class="panel-body">
                <h4 class="panel-title">
                    <a href="{{ url_for('metadata.get', id=metadata.id) }}">
                    {{ metadata.title }}
                    </a>
                    <div class="btn-group">
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">view</a></li>
                            <li><a href="#">edit</a></li>
                            <form id="metadata_delete_form" method="POST" action="{{ url_for('metadata.delete', id=metadata.id) }}">
                                <input type="hidden" name="id" id="metadata_delete_id" value="{{ metadata.id }}">
                                <input type="hidden" name="url" id="metadata_delete_url" value="{{ url_for('metadata.delete', id=metadata.id) }}">
                                <li>
                                    <button type="submit"><span class="glyphicon glyphicon-remove"></span> delete</button>
                                </li>
                            </form>
                        </ul>
                    </div>
                </h4>
                <p>{{ metadata.desc }}</p>
            </div> -->
        <!-- </div> -->
        {% endfor %}
    {% endblock %}
</div>
    
{% endblock %}

{% block add_scripts %}

  <script>
    console.log('test 123')
    
  </script>
  
{% endblock %}